[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "tethysapp-fimeval_gui"
description = "Webapp GUI for FIMeval"

keywords = []
authors = [
    {name = "Reshma Raghavan", email = "rraghavan@aquaveo.com"},
]
classifiers = [
     "Environment :: Web Environment",
     "Framework :: Django",
     "Intended Audience :: Developers",
     "Operating System :: OS Independent",
     "Programming Language :: Python",
     "Programming Language :: Python :: 3",
     "Programming Language :: Python :: 3.10",
     "Topic :: Internet :: WWW/HTTP",
     "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dependencies = [
    "fimeval>=0.1.64",
    "boto3",
    "dask[distributed]",
    "rio-tiler",
]
dynamic = ["version"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]

[tool.setuptools.package-data]
"tethysapp.fimeval_gui" = [
    "templates/**/*",
    "public/**/*",
    "workspaces/**/*"
]
