fullnameOverride: fimeval

image:
  repository: gioelkin/tethysapp-fimeval-gui
  tag: latest
  pullPolicy: Always

tethys:
  mode: single
  standaloneApp: fimeval_gui
  publicProtocol: https
  persist:
    enabled: true

externalDatabase:
  host: ciroh-portal-db.cfmp1axs2tbt.us-east-1.rds.amazonaws.com
  port: 5432
  name: tethys_platform
  username: tethys_default

secrets:
  existingSecretName: fimeval-secrets
  secretEnv:
    - name: HYDROSHARE_CLIENT_ID
      key: HYDROSHARE_CLIENT_ID
    - name: HYDROSHARE_SECRET_ID
      key: HYDROSHARE_SECRET_ID

serviceAccount:
  create: true
  name: fimeval-dask
  roleArn: arn:aws:iam::456531024327:role/fimeval-s3-irsa

ingress:
  enabled: true
  className: alb
  host: fimeval.tethys.ciroh.org
  annotations:
    alb.ingress.kubernetes.io/group.name: ciroh-portal
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'

portalConfig:
  settings:
    AUTHENTICATION_BACKENDS:
      - tethys_services.backends.hydroshare.HydroShareOAuth2
    OAUTH_CONFIG:
      OAUTH2_PROVIDER:
        OIDC_ENABLED: true
        PKCE_REQUIRED: true

dask:
  enabled: true
  worker:
    nthreads: 2
    memoryLimit: 12GiB
    scratchSize: 20Gi
    nodeSelector:
      karpenter.sh/capacity-type: spot
    env:
      FIMEVAL_TARGET_CRS: EPSG:5070
  autoscaler:
    minimum: 0
    maximum: 4

pdb:
  enabled: true
hpa:
  enabled: false
